
version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Downloading source code 
      - git clone https://github.com/OISF/libhtp -b 0.5.x
      - |
          cd suricata-update
          curl -L \
              https://github.com/OISF/suricata-update/archive/master.tar.gz | \
              tar zxvf - --strip-components=1
      - cd ..
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region eu-west-1 --no-include-email)
      - REPOSITORY_URI=389941814333.dkr.ecr.eu-west-1.amazonaws.com/alpine/suricata
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:  
      - echo Building docker image
      - docker build -t $REPOSITORY_URI:latest .
      - export SURICATA_VERSION="$(docker run $REPOSITORY_URI:latest /usr/bin/suricata -V | awk '{print $5}')"
      - docker tag $REPOSITORY_URI:latest "$REPOSITORY_URI:${SURICATA_VERSION}" 
  post_build:
    commands: 
      - echo Pushing Docker images
      - docker push $REPOSITORY_URI:latest
      - docker push "$REPOSITORY_URI:${SURICATA_VERSION}"
