
version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Downloading source code 
      - git clone https://github.com/OISF/libhtp -b 0.5.x
      - |
          cd suricata-update
          curl -L \
              https://github.com/OISF/suricata-update/archive/master.tar.gz | \
              tar zxvf - --strip-components=1
      - cd ..
  build:
    commands:  
      - echo do docker build here
      - docker build -t alpine/suricata:latest .
      - docker run -t alpine/suricata:latest /usr/bin/suricata -V
  post_build:
    commands:
      - echo uploading to ecr
